name: dev
description: Generate Amazing Images
publish_to: 'none'
version: 1.5.7+186

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependency_overrides:
  win32: ^5.5.4

dependencies:
  app_links: ^6.0.1
  crypto: ^3.0.3
  dio: ^5.3.2
  fast_image_resizer: ^0.0.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_avif: ^2.4.1
  flutter_contacts: ^1.1.7+1
  flutter_image_compress: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_signin_button: ^2.0.0

  fluttertoast: ^8.2.2
  gamma_smart_pagination: ^1.0.5
  go_router: ^14.0.2
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  http_parser: ^4.0.2
  icons_plus: ^5.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.2
  image_size_getter: ^2.1.2
  in_app_purchase: ^3.1.8
  in_app_purchase_storekit: ^0.3.6+5
  loading_animation_widget: ^1.2.0+4
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.1.0
  photo_view: ^0.15.0
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  reflectable: ^4.0.5
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^6.1.0
  social_share: ^2.3.1
  time_machine: ^0.9.17
  url_launcher: ^6.1.12
  uuid: ^4.4.2
  video_player: ^2.7.2
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.2.2
  flutter_test:
    sdk: flutter
  in_app_review: ^2.0.8
  flutter_reactive_value: ^2.0.1
  firebase_analytics: ^10.6.1
  facebook_app_events: ^0.19.0
  app_tracking_transparency: ^2.0.4
  widget_zoom: ^0.0.2
  cupertino_icons: ^1.0.6
  upgrader: ^10.3.0
  social_share_plugin: ^0.4.2+2
  # google_mlkit_image_labeling:
  google_mobile_ads:
    git:
      url: https://github.com/googleads/googleads-mobile-flutter.git
      ref: main
      path: packages/google_mobile_ads
  share_plus: ^9.0.0
  http: ^1.2.1
  markdown_widget: ^2.3.1
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.7.1
  firebase_crashlytics: ^3.4.9
  applovin_max: any
  flutter_webrtc: ^0.11.3
  fetch_client: ^1.1.2
  intl: ^0.19.0
  audio_waveforms: ^1.0.5
  flutter_sound: ^9.6.0
  flutter_audio_waveforms: ^1.2.1+8
  audioplayers: ^6.1.0
  video_compress: ^3.1.3
  flutter_callkit_incoming: ^2.0.4+1
  ffmpeg_kit_flutter_audio: ^6.0.3
  notification_permissions: ^0.6.1

dev_dependencies:
  flutter_lints: ^3.0.2
  build_runner: ^2.4.6

# dependency_overrides:
#   in_app_purchase_android: 0.2.2+8


flutter:
  uses-material-design: true
  assets:
    - assets/style_images/3d-model.png
    - assets/style_images/anime.png
    - assets/style_images/digital-art-2.png
    - assets/style_images/digital-art.png
    - assets/style_images/fantasy-art.png
    - assets/style_images/photorealistic.png
    - assets/style_images/none.png
    - assets/ml_models/
    - assets/images/
    - assets/icon.png
    - assets/compare_image_quality/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "assets/icon.png"
